// src/constants.js

export const CHRONIC_CONDITIONS = [
  "Diabetes",
  "Hypertension",
  "Asthma",
  "Chronic Kidney Disease",
  "Heart Disease",
  "Arthritis",
  "Chronic Obstructive Pulmonary Disease (COPD)",
  "Thyroid Disorder",
  "Depression",
  "Anxiety",
  "Cancer",
  "HIV/AIDS",
  "Epilepsy",
  "Tuberculosis (TB)",
  "Migraine",
];

export const ALLERGIES = [
  "Peanuts",
  "Tree Nuts",
  "Milk",
  "Eggs",
  "Wheat",
  "Soy",
  "Fish",
  "Shellfish",
  "Pollen",
  "Dust Mites",
  "Pet Dander",
  "Insect Stings",
  "Mold",
  "Latex",
  "Penicillin",
];

export const SYMPTOMS = [
  "Fever",
  "Cough",
  "Shortness of Breath",
  "Fatigue",
  "Headache",
  "Sore Throat",
  "Chest Pain",
  "Nausea",
  "Vomiting",
  "Diarrhea",
  "Muscle Pain",
  "Joint Pain",
  "Dizziness",
  "Loss of Taste",
  "Loss of Smell",
];
